/** @type {import('next').NextConfig} */
const nextConfig = {
     async redirects() {
      return [
        {
          source: '/',
          destination: '/pages/orders',
          permanent: false,
          
        },
      ];
},
    async headers() {
      return [
        {
          source: '/',
          headers: [
            {
              key: 'title',
              value: 'Scentique',
            },
            {
              key: 'description',
              value: 'Generated by create next app',
            },
          ],
        },
      ];
    },
};

export default nextConfig;
